name: Feature Branch Validation

on:
  pull_request:
    branches:
      - 'feature/**'
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK (example)
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Build application
        run: ./scripts/build.sh
        
      - name: Run tests
        run: ./scripts/test.sh
        
      - name: Code coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml